# -----------------------------------------------
# Jekyll Configuration
# -----------------------------------------------

markdown: rdiscount
permalink: pretty
pygments: true

# -----------------------------------------------
# Site-specific Settings
# -----------------------------------------------

author: Leo Martel
author_email: leo@lpm.io
title: Lpm.io
url: http://localhost:4000
# url: http://lpm.io
