# -----------------------------------------------
# Jekyll Configuration
# -----------------------------------------------

markdown: rdiscount
permalink: pretty
pygments: true

# -----------------------------------------------
# Site-specific Settings
# -----------------------------------------------

author: Leo Martel
author_email: leo@lpm.io
title: Lpm.io
# url: http://localhost:4000     # Development
url: http://lpm.io               # Production
github_url: http://github.com/lmartel
linkedin_url: http://www.linkedin.com/in/leopmartel/

axisandallies_url: http://game.lpm.io
hexmoney_url: http://lpm.io/HexMoney
chinesecheckers_url: http://lpm.io/ChineseCheckers
tvtracker_url: http://tv.lpm.io
harmonics_url: http://harmonics.herokuapp.com

resume_url: https://dl.dropboxusercontent.com/u/84750930/leo_martel_resume.pdf
resume_date: February 7, 2014
